export const productData = [
  {
    key: 0,
    id: 0,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Национальная',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    price: 15,
    restorant: "Лагман Хаус",
    restorantMenuCategory: "Ролы",
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    additions: {
      additionsNames: ["Палочки 1шт", "Васаби", "Васаби", "Соевый соус", "Имбирь", "Имбирь"],
      additionsPrices: [0.00, 5.00, 5.00, 7.00, 5.00, 5.00]
    },
    fullDesc: "Безусловно, понимание сути ресурсосберегающих технологий создаёт предпосылки для своевременного выполнения сверхзадачи. Равным образом, базовый вектор развития говорит о возможностях дальнейших направлений развития.",
  },
  {
    key: 1,
    id: 1,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Национальная',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Лагман Хаус",
  },
  {
    key: 2,
    id: 2,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Национальная',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Лагман Хаус",
  },
  {
    key: 3,
    id: 3,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Национальная',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Лагман Хаус",
  },
  {
    key: 4,
    id: 4,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Национальная',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Лагман Хаус",
  },
  {
    key: 5,
    id: 5,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Национальная',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Лагман Хаус",
  },
  {
    key: 6,
    id: 6,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Национальная',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Лагман Хаус",
  },
  {
    key: 7,
    id: 7,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Национальная',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Лагман Хаус",
  },
  {
    key: 8,
    id: 8,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Ролы',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Лагман Хаус",
  },
  {
    key: 9,
    id: 9,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Ролы',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Лагман Хаус",
  },
  {
    key: 10,
    id: 10,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Ролы',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Якитория",
  },
  {
    key: 11,
    id: 11,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Ролы',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Якитория",
  },
  {
    key: 12,
    id: 12,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Суши',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Якитория",
  },
  {
    key: 13,
    id: 13,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Суши',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Якитория",
  },
  {
    key: 14,
    id: 14,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Суши',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Якитория",
  },
  {
    key: 15,
    id: 15,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Сеты',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Якитория",
  },
  {
    key: 16,
    id: 16,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Сеты',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Якитория",
  },
  {
    key: 17,
    id: 17,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Сеты',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Якитория",
  },
  {
    key: 18,
    id: 18,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Сеты',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Якитория",
  },
  {
    key: 19,
    id: 19,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Сеты',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Якитория",
  },
  {
    key: 20,
    id: 20,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Сеты',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Якитория",
  },
  {
    key: 21,
    id: 21,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Сеты',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Якитория",
  },
  {
    key: 22,
    id: 22,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Сашими',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Якитория",
  },
  {
    key: 23,
    id: 23,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Сашими',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Якитория",
  },
  {
    key: 24,
    id: 24,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Сашими',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Якитория",
  },
  {
    key: 25,
    id: 25,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Сашими',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Якитория",
  },
  {
    key: 26,
    id: 26,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Сашими',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Якитория",
  },
  {
    key: 27,
    id: 27,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Сашими',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Якитория",
  },
  {
    key: 28,
    id: 28,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Сашими',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Якитория",
  },
  {
    key: 29,
    id: 29,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Десерты',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Якитория",
  },
  {
    key: 30,
    id: 30,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Десерты',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Якитория",
  },
  {
    key: 31,
    id: 31,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Десерты',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Якитория",
  },
  {
    key: 32,
    id: 32,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Десерты',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Якитория",
  },
  {
    key: 33,
    id: 33,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Десерты',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Якитория",
  },
  {
    key: 34,
    id: 34,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Десерты',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Якитория",
  },
  {
    key: 35,
    id: 35,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Десерты',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Якитория",
  },
  {
    key: 36,
    id: 36,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Десерты',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Якитория",
  },
  {
    key: 37,
    id: 37,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Напитки',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Якитория",
  },
  {
    key: 38,
    id: 38,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Напитки',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Якитория",
  },
  {
    key: 39,
    id: 39,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Напитки',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Якитория",
  },
  {
    key: 40,
    id: 40,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Напитки',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Якитория",
  },
  {
    key: 41,
    id: 41,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Напитки',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Якитория",
  },
  {
    key: 42,
    id: 42,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Напитки',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Якитория",
  },
  {
    key: 43,
    id: 43,
    image: 'img/product.svg',
    title: 'Плов Бародарон',
    category: 'Напитки',
    discount: 20,
    rate: 4.5,
    numberOfRates: 129,
    productDesc: "Дайкон, Капуста белокочанная, Морковь, Огурцы, Зелень.",
    price: 15,
    restorant: "Якитория",
  },
]