export const restorantsData = [
  {
    id: "sambusa",
    name: "Самбуса №1",
    bannerImage: "/img/restorant-banner.svg",
    sliderText: "Свежие морепродукты",
    logo: "img/sambusa.svg",
    mainPageImage: "img/sambusa-img.svg",
    category: "Грузинская",
    fullDesc: "Сеть культовых ресторанов авторской национальная кухни…",
    address: "Н.Махсум 77/5 А",
    isAdvertised: true,
    menuCategories: ["Долма", "Плов", "Лагман", "Суп", "Стейк", "Напитки"],
    sale: {
      saleTitle: "Скидка 20%",
      saleDesc: "При заказе от 100 сом.",
      saleType: 'discount',
    },
    mainSliderText: "Свежие морепродукты",
    minDeliveryPrice: 5,
    minOrderPrice: 30,
    rate: 4.5,
    numberOfRates: 129,
    deliveryTime: "50-60 мин",
    workingSchadule: "с 8:00 до 22:00",
  },
  {
    id: "omar-hayyam",
    name: "Омар Хайям",
    bannerImage: "/img/restorant-banner.svg",
    sliderText: "Свежие морепродукты",
    logo: "img/omar-hayyam.svg",
    mainPageImage: "img/sambusa-img.svg",
    category: "Арабская",
    fullDesc: "Сеть культовых ресторанов авторской национальная кухни…",
    address: "Н.Махсум 77/5 А",
    isAdvertised: true,
    menuCategories: ["Долма", "Плов", "Лагман", "Суп", "Стейк", "Напитки"],
    sale: {
      saleTitle: "Блюдо в подарок",
      saleDesc: "При заказе от 100 сом.",
      saleType: 'gift',
    },
    mainSliderText: "Свежие морепродукты",
    minDeliveryPrice: 5,
    minOrderPrice: 30,
    rate: 4.5,
    numberOfRates: 129,
    deliveryTime: "50-60 мин",
    workingSchadule: "с 8:00 до 22:00",
  },
  {
    id: "lagman-haus",
    name: "Лагман Хаус",
    bannerImage: "/img/restorant-banner.svg",
    sliderText: "Свежие морепродукты",
    logo: "img/lagman-hause.svg",
    mainPageImage: "img/lagman-hause-img.svg",
    category: "Турецкая",
    fullDesc: "Сеть культовых ресторанов авторской национальная кухни…",
    address: "Н.Махсум 77/5 А",
    isAdvertised: false,
    menuCategories: ["Долма", "Плов", "Лагман", "Суп", "Напитки"],
    sale: {
      saleTitle: "Бесплатная доставка",
      saleDesc: "Мин. заказ 100 сом",
      saleType: 'delivery',
    },
    mainSliderText: "Свежие морепродукты",
    minDeliveryPrice: 5,
    minOrderPrice: 30,
    rate: 4.5,
    numberOfRates: 129,
    deliveryTime: "50-60 мин",
    workingSchadule: "с 8:00 до 22:00",
  },
  {
    id: "yakitoriya",
    name: "Якитория",
    bannerImage: "/img/restorant-banner.svg",
    sliderText: "Свежие морепродукты",
    logo: "img/lagman-hause.svg",
    mainPageImage: "img/lagman-hause-img.svg",
    category: "Японская кухня",
    fullDesc: "Сеть культовых ресторанов авторской японской кухни…",
    address: "Н.Махсум 77/5 А",
    isAdvertised: true,
    menuCategories: ["Ролы", "Суши", "Сеты", "Сашими", "Десерты", "Напитки"],
    sale: {
      saleTitle: "Скидка 20%",
      saleDesc: "При заказе от 100 сом.",
      saleType: 'discount',
    },
    mainSliderText: "Свежие морепродукты",
    minDeliveryPrice: 5,
    minOrderPrice: 30,
    rate: 4.5,
    numberOfRates: 129,
    deliveryTime: "50-60 мин",
    workingSchadule: "с 8:00 до 22:00",
  },
  {
    id: "yakitoriya2",
    name: "Якитория2",
    bannerImage: "/img/restorant-banner.svg",
    sliderText: "Свежие морепродукты",
    logo: "img/lagman-hause.svg",
    mainPageImage: "img/lagman-hause-img.svg",
    category: "Корейская",
    fullDesc: "Сеть культовых ресторанов авторской японской кухни…",
    address: "Н.Махсум 77/5 А",
    isAdvertised: true,
    menuCategories: ["Ролы", "Суши", "Сеты", "Сашими", "Десерты", "Напитки"],
    sale: {
      saleTitle: "Блюдо в подарок",
      saleDesc: "При заказе от 100 сом.",
      saleType: 'gift',
    },
    mainSliderText: "Свежие морепродукты",
    minDeliveryPrice: 5,
    minOrderPrice: 30,
    rate: 4.5,
    numberOfRates: 129,
    deliveryTime: "50-60 мин",
    workingSchadule: "с 8:00 до 22:00",
  },
  {
    id: "lagman-haus2",
    name: "Лагман Хаус2",
    bannerImage: "/img/restorant-banner.svg",
    sliderText: "Свежие морепродукты",
    logo: "img/lagman-hause.svg",
    mainPageImage: "img/lagman-hause-img.svg",
    category: "Индийская",
    fullDesc: "Сеть культовых ресторанов авторской японской кухни…",
    address: "Н.Махсум 77/5 А",
    isAdvertised: true,
    menuCategories: ["Ролы", "Суши", "Сеты", "Сашими", "Десерты", "Напитки"],
    sale: {
      saleTitle: "Бесплатная доставка",
      saleDesc: "Мин. заказ 100 сом",
      saleType: 'delivery',
    },
    mainSliderText: "Свежие морепродукты",
    minDeliveryPrice: 5,
    minOrderPrice: 30,
    rate: 4.5,
    numberOfRates: 129,
    deliveryTime: "50-60 мин",
    workingSchadule: "с 8:00 до 22:00",
  },
  {
    id: "khan-chapan",
    name: "Khan Chapan",
    bannerImage: "/img/restorant-banner.svg",
    sliderText: "Свежие морепродукты",
    logo: "img/lagman-hause.svg",
    mainPageImage: "img/khan-chapan-img.svg",
    category: "Осетинская",
    fullDesc: "Сеть культовых ресторанов авторской японской кухни…",
    address: "Н.Махсум 77/5 А",
    isAdvertised: true,
    menuCategories: ["Ролы", "Суши", "Сеты", "Сашими", "Десерты", "Напитки"],
    sale: {
      saleTitle: "Блюдо в подарок",
      saleDesc: "При заказе от 100 сом.",
      saleType: 'gift',
    },
    mainSliderText: "Свежие морепродукты",
    minDeliveryPrice: 5,
    minOrderPrice: 30,
    rate: 4.5,
    numberOfRates: 129,
    deliveryTime: "50-60 мин",
    workingSchadule: "с 8:00 до 22:00",
  },
  {
    id: "khan-chapan2",
    name: "Khan Chapan2",
    bannerImage: "/img/restorant-banner.svg",
    sliderText: "Свежие морепродукты",
    logo: "img/lagman-hause.svg",
    mainPageImage: "img/khan-chapan-img.svg",
    category: "Осетинская",
    fullDesc: "Сеть культовых ресторанов авторской японской кухни…",
    address: "Н.Махсум 77/5 А",
    isAdvertised: true,
    menuCategories: ["Ролы", "Суши", "Сеты", "Сашими", "Десерты", "Напитки"],
    sale: {
      saleTitle: "Блюдо в подарок",
      saleDesc: "При заказе от 100 сом.",
      saleType: 'gift',
    },
    mainSliderText: "Свежие морепродукты",
    minDeliveryPrice: 5,
    minOrderPrice: 30,
    rate: 4.5,
    numberOfRates: 129,
    deliveryTime: "50-60 мин",
    workingSchadule: "с 8:00 до 22:00",
  },
]